### PR TITLE
enabled the command and fixed some things

### PR DESCRIPTION
**Pull request by ghost**
fixed lastsearch, id, rating, and score.

### CODE REVIEW

**Comment by ineeee** [comment]
this doesnt work because `f"{var}"` isnt available in python 2

**Comment by ghost** [comment]
update: fixed format string, it should work fine now

**Comment by ineeee** [comment]
the command doesnt work:
```
06:30:21 #test <inex> .e621 cat
Tell Database Ready
Unhandled exception in thread started by <function run at 0x7f9329afc9d0>
Traceback (most recent call last):
  File "core/main.py", line 71, in run
    out = func(input.inp)
  File "plugins/furry.py", line 40, in furry
    if not inp in lastsearch or len(furry_cache) < 2: refresh_cache(inp)
  File "plugins/furry.py", line 19, in refresh_cache
    posts = postjson.posts
AttributeError: 'dict' object has no attribute 'posts'
```

**Comment by ghost** [comment]
Fixed these errors :+1:

**Review by ineeee — APPROVED** [review]
looks good to me, i tested and works

**Pull request merged**
